[project]
name = "hotel-matching"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "imagehash>=4.3.2",
    "pillow>=11.3.0",
    "torch>=2.8.0",
    "transformers>=4.56.1",
]
